export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as New } from './New'
export { default as OnBoarding } from './OnBoarding'
export { default as Home } from './Home'
export { default as DestinationDetail } from './DestinationDetail'
export { default as Analysis } from './Analysis'
export { default as Services } from './Services'
export { default as BookDetail } from './BookDetail'
export { default as Tree } from './Tree'
export { default as PlantDetail } from './PlantDetail'

